on: [push]
jobs:
  exec-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action-a
        id: time
      - uses: ./action-b
        with:
          time: ${{ steps.time.outputs.time }}